platform :ios, '13.0'

target 'FlareSDKSample' do
use_frameworks!
pod 'IQKeyboardManager', '~> 6.5'
#pod 'SideEngine-iOS'
pod 'SideEngine-iOS', :git => 'https://github.com/tnmrajesh/TechML.git', :tag => '4.2.5'
end
