#workspace '/Users/phoenix/Documents/K-Safe/iOS-SDK/Develop/busbysdk_ios/SDKSampleApp.xcworkspace'
platform :ios, '13.0'

target 'FlareSDKSample' do
use_frameworks!
pod 'IQKeyboardManager'
pod 'SideEngine-iOS', '4.3.3'
end
