# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlareSDKSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideEngine-iOS', '4.0.3'
  pod 'IQKeyboardManager', '~> 6.5'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
#  pod 'FirebaseCrashlytics'
  pod 'Firebase/Crashlytics'
end
